listen = "0.0.0.0:5258"
switch-keys = ["LeftAlt", "LeftCtrl"]
certificate = "/etc/rkvm/certificate.pem"
key = "/etc/rkvm/key.pem"

# This is to prevent malicious clients from connecting to the server.
# Make sure this matches your client's config.
#
# Change this to your own value before deploying rkvm.
password = "123456789"
